// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE5zSA8Jzj0V-vfLYKbygm1_gj5Kf-dRg',
    appId: '1:730567865597:web:973801e875074e11ce3a94',
    messagingSenderId: '730567865597',
    projectId: 'ritvik-608cd',
    authDomain: 'ritvik-608cd.firebaseapp.com',
    databaseURL: 'https://ritvik-608cd-default-rtdb.firebaseio.com',
    storageBucket: 'ritvik-608cd.firebasestorage.app',
    measurementId: 'G-9E75CR1WVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEV92AuryP2TUq4bIEjsJ4lQHTDAQrwOE',
    appId: '1:730567865597:android:8ff9bf1dd93aede6ce3a94',
    messagingSenderId: '730567865597',
    projectId: 'ritvik-608cd',
    databaseURL: 'https://ritvik-608cd-default-rtdb.firebaseio.com',
    storageBucket: 'ritvik-608cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYR28dZt_Ji2OPQIEHPz73HbZ1Ez02XgM',
    appId: '1:730567865597:ios:fbe65d66d9f097dece3a94',
    messagingSenderId: '730567865597',
    projectId: 'ritvik-608cd',
    databaseURL: 'https://ritvik-608cd-default-rtdb.firebaseio.com',
    storageBucket: 'ritvik-608cd.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYR28dZt_Ji2OPQIEHPz73HbZ1Ez02XgM',
    appId: '1:730567865597:ios:fbe65d66d9f097dece3a94',
    messagingSenderId: '730567865597',
    projectId: 'ritvik-608cd',
    databaseURL: 'https://ritvik-608cd-default-rtdb.firebaseio.com',
    storageBucket: 'ritvik-608cd.firebasestorage.app',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE5zSA8Jzj0V-vfLYKbygm1_gj5Kf-dRg',
    appId: '1:730567865597:web:71bb4a6523d5a11dce3a94',
    messagingSenderId: '730567865597',
    projectId: 'ritvik-608cd',
    authDomain: 'ritvik-608cd.firebaseapp.com',
    databaseURL: 'https://ritvik-608cd-default-rtdb.firebaseio.com',
    storageBucket: 'ritvik-608cd.firebasestorage.app',
    measurementId: 'G-V6EZCWRP5N',
  );
}
